// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 21 Jun 2021 16:17:37 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "beagle.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

