// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 21 Jun 2021 16:17:37 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package beagle_bindings

/*
#cgo LDFLAGS: -L${SRCDIR} -lstdc++
#cgo CFLAGS: -I. -DDEBUG -I${SRCDIR}/
#include "beagle.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// BG_DEBUG as defined in beagle/beagle.h:101
	BG_DEBUG = 0
	// BG_HEADER_VERSION as defined in beagle/beagle.h:107
	BG_HEADER_VERSION = 1320
	// BG_PORT_NOT_FREE as defined in beagle/beagle.h:276
	BG_PORT_NOT_FREE = 32768
	// BG_FEATURE_NONE as defined in beagle/beagle.h:374
	BG_FEATURE_NONE = 0
	// BG_FEATURE_I2C as defined in beagle/beagle.h:375
	BG_FEATURE_I2C = 1
	// BG_FEATURE_SPI as defined in beagle/beagle.h:376
	BG_FEATURE_SPI = 2
	// BG_FEATURE_USB as defined in beagle/beagle.h:377
	BG_FEATURE_USB = 4
	// BG_FEATURE_MDIO as defined in beagle/beagle.h:378
	BG_FEATURE_MDIO = 8
	// BG_FEATURE_USB_HS as defined in beagle/beagle.h:379
	BG_FEATURE_USB_HS = 16
	// BG_FEATURE_USB_SS as defined in beagle/beagle.h:380
	BG_FEATURE_USB_SS = 32
	// BG_TARGET_POWER_OFF as defined in beagle/beagle.h:458
	BG_TARGET_POWER_OFF = 0
	// BG_TARGET_POWER_ON as defined in beagle/beagle.h:459
	BG_TARGET_POWER_ON = 1
	// BG_TARGET_POWER_QUERY as defined in beagle/beagle.h:460
	BG_TARGET_POWER_QUERY = 128
	// BG_HOST_IFCE_FULL_SPEED as defined in beagle/beagle.h:467
	BG_HOST_IFCE_FULL_SPEED = 0
	// BG_HOST_IFCE_HIGH_SPEED as defined in beagle/beagle.h:468
	BG_HOST_IFCE_HIGH_SPEED = 1
	// BG_HOST_IFCE_SUPER_SPEED as defined in beagle/beagle.h:469
	BG_HOST_IFCE_SUPER_SPEED = 2
	// BG_READ_OK as defined in beagle/beagle.h:534
	BG_READ_OK = 0
	// BG_READ_TIMEOUT as defined in beagle/beagle.h:535
	BG_READ_TIMEOUT = 256
	// BG_READ_ERR_MIDDLE_OF_PACKET as defined in beagle/beagle.h:536
	BG_READ_ERR_MIDDLE_OF_PACKET = 512
	// BG_READ_ERR_SHORT_BUFFER as defined in beagle/beagle.h:537
	BG_READ_ERR_SHORT_BUFFER = 1024
	// BG_READ_ERR_PARTIAL_LAST_BYTE as defined in beagle/beagle.h:538
	BG_READ_ERR_PARTIAL_LAST_BYTE = 2048
	// BG_READ_ERR_PARTIAL_LAST_BYTE_MASK as defined in beagle/beagle.h:539
	BG_READ_ERR_PARTIAL_LAST_BYTE_MASK = 15
	// BG_READ_ERR_UNEXPECTED as defined in beagle/beagle.h:540
	BG_READ_ERR_UNEXPECTED = 4096
	// BG_I2C_PULLUP_OFF as defined in beagle/beagle.h:618
	BG_I2C_PULLUP_OFF = 0
	// BG_I2C_PULLUP_ON as defined in beagle/beagle.h:619
	BG_I2C_PULLUP_ON = 1
	// BG_I2C_PULLUP_QUERY as defined in beagle/beagle.h:620
	BG_I2C_PULLUP_QUERY = 128
	// BG_I2C_MONITOR_DATA as defined in beagle/beagle.h:627
	BG_I2C_MONITOR_DATA = 255
	// BG_I2C_MONITOR_NACK as defined in beagle/beagle.h:628
	BG_I2C_MONITOR_NACK = 256
	// BG_READ_I2C_NO_STOP as defined in beagle/beagle.h:629
	BG_READ_I2C_NO_STOP = 65536
	// BG_USB_PID_OUT as defined in beagle/beagle.h:751
	BG_USB_PID_OUT = 225
	// BG_USB_PID_IN as defined in beagle/beagle.h:752
	BG_USB_PID_IN = 105
	// BG_USB_PID_SOF as defined in beagle/beagle.h:753
	BG_USB_PID_SOF = 165
	// BG_USB_PID_SETUP as defined in beagle/beagle.h:754
	BG_USB_PID_SETUP = 45
	// BG_USB_PID_DATA0 as defined in beagle/beagle.h:755
	BG_USB_PID_DATA0 = 195
	// BG_USB_PID_DATA1 as defined in beagle/beagle.h:756
	BG_USB_PID_DATA1 = 75
	// BG_USB_PID_DATA2 as defined in beagle/beagle.h:757
	BG_USB_PID_DATA2 = 135
	// BG_USB_PID_MDATA as defined in beagle/beagle.h:758
	BG_USB_PID_MDATA = 15
	// BG_USB_PID_ACK as defined in beagle/beagle.h:759
	BG_USB_PID_ACK = 210
	// BG_USB_PID_NAK as defined in beagle/beagle.h:760
	BG_USB_PID_NAK = 90
	// BG_USB_PID_STALL as defined in beagle/beagle.h:761
	BG_USB_PID_STALL = 30
	// BG_USB_PID_NYET as defined in beagle/beagle.h:762
	BG_USB_PID_NYET = 150
	// BG_USB_PID_PRE as defined in beagle/beagle.h:763
	BG_USB_PID_PRE = 60
	// BG_USB_PID_ERR as defined in beagle/beagle.h:764
	BG_USB_PID_ERR = 60
	// BG_USB_PID_SPLIT as defined in beagle/beagle.h:765
	BG_USB_PID_SPLIT = 120
	// BG_USB_PID_PING as defined in beagle/beagle.h:766
	BG_USB_PID_PING = 180
	// BG_USB_PID_EXT as defined in beagle/beagle.h:767
	BG_USB_PID_EXT = 240
	// BG_USB_PID_CORRUPTED as defined in beagle/beagle.h:768
	BG_USB_PID_CORRUPTED = 255
	// BG_READ_USB_ERR_BAD_SIGNALS as defined in beagle/beagle.h:770
	BG_READ_USB_ERR_BAD_SIGNALS = 65536
	// BG_READ_USB_ERR_BAD_PID as defined in beagle/beagle.h:771
	BG_READ_USB_ERR_BAD_PID = 2097152
	// BG_READ_USB_ERR_BAD_CRC as defined in beagle/beagle.h:772
	BG_READ_USB_ERR_BAD_CRC = 4194304
	// BG_READ_USB_ERR_BAD_SYNC as defined in beagle/beagle.h:774
	BG_READ_USB_ERR_BAD_SYNC = 131072
	// BG_READ_USB_ERR_BIT_STUFF as defined in beagle/beagle.h:775
	BG_READ_USB_ERR_BIT_STUFF = 262144
	// BG_READ_USB_ERR_FALSE_EOP as defined in beagle/beagle.h:776
	BG_READ_USB_ERR_FALSE_EOP = 524288
	// BG_READ_USB_ERR_LONG_EOP as defined in beagle/beagle.h:777
	BG_READ_USB_ERR_LONG_EOP = 1048576
	// BG_READ_USB_TRUNCATION_LEN_MASK as defined in beagle/beagle.h:779
	BG_READ_USB_TRUNCATION_LEN_MASK = 255
	// BG_READ_USB_TRUNCATION_MODE as defined in beagle/beagle.h:780
	BG_READ_USB_TRUNCATION_MODE = 536870912
	// BG_READ_USB_END_OF_CAPTURE as defined in beagle/beagle.h:781
	BG_READ_USB_END_OF_CAPTURE = 1073741824
	// BG_READ_USB_ERR_BAD_SLC_CRC_1 as defined in beagle/beagle.h:783
	BG_READ_USB_ERR_BAD_SLC_CRC_1 = 32768
	// BG_READ_USB_ERR_BAD_SLC_CRC_2 as defined in beagle/beagle.h:784
	BG_READ_USB_ERR_BAD_SLC_CRC_2 = 65536
	// BG_READ_USB_ERR_BAD_SHP_CRC_16 as defined in beagle/beagle.h:785
	BG_READ_USB_ERR_BAD_SHP_CRC_16 = 32768
	// BG_READ_USB_ERR_BAD_SHP_CRC_5 as defined in beagle/beagle.h:786
	BG_READ_USB_ERR_BAD_SHP_CRC_5 = 65536
	// BG_READ_USB_ERR_BAD_SDP_CRC as defined in beagle/beagle.h:787
	BG_READ_USB_ERR_BAD_SDP_CRC = 32768
	// BG_READ_USB_EDB_FRAMING as defined in beagle/beagle.h:788
	BG_READ_USB_EDB_FRAMING = 131072
	// BG_READ_USB_ERR_UNK_END_OF_FRAME as defined in beagle/beagle.h:789
	BG_READ_USB_ERR_UNK_END_OF_FRAME = 262144
	// BG_READ_USB_ERR_DATA_LEN_INVALID as defined in beagle/beagle.h:790
	BG_READ_USB_ERR_DATA_LEN_INVALID = 524288
	// BG_READ_USB_PKT_TYPE_LINK as defined in beagle/beagle.h:791
	BG_READ_USB_PKT_TYPE_LINK = 1048576
	// BG_READ_USB_PKT_TYPE_HDR as defined in beagle/beagle.h:792
	BG_READ_USB_PKT_TYPE_HDR = 2097152
	// BG_READ_USB_PKT_TYPE_DP as defined in beagle/beagle.h:793
	BG_READ_USB_PKT_TYPE_DP = 4194304
	// BG_READ_USB_PKT_TYPE_TSEQ as defined in beagle/beagle.h:794
	BG_READ_USB_PKT_TYPE_TSEQ = 8388608
	// BG_READ_USB_PKT_TYPE_TS1 as defined in beagle/beagle.h:795
	BG_READ_USB_PKT_TYPE_TS1 = 16777216
	// BG_READ_USB_PKT_TYPE_TS2 as defined in beagle/beagle.h:796
	BG_READ_USB_PKT_TYPE_TS2 = 33554432
	// BG_READ_USB_ERR_BAD_TS as defined in beagle/beagle.h:797
	BG_READ_USB_ERR_BAD_TS = 67108864
	// BG_READ_USB_ERR_FRAMING as defined in beagle/beagle.h:798
	BG_READ_USB_ERR_FRAMING = 134217728
	// BG_READ_USBPD_BIT_LEN_MASK as defined in beagle/beagle.h:800
	BG_READ_USBPD_BIT_LEN_MASK = 1792
	// BG_READ_USBPD_BIT_LEN_SHIFT as defined in beagle/beagle.h:801
	BG_READ_USBPD_BIT_LEN_SHIFT = 8
	// BG_READ_USBPD_PARSE_ERR_MASK as defined in beagle/beagle.h:802
	BG_READ_USBPD_PARSE_ERR_MASK = 15
	// BG_READ_USBPD_NO_PREAMBLE as defined in beagle/beagle.h:803
	BG_READ_USBPD_NO_PREAMBLE = 1
	// BG_READ_USBPD_NO_SOP as defined in beagle/beagle.h:804
	BG_READ_USBPD_NO_SOP = 2
	// BG_READ_USBPD_NO_HEADER as defined in beagle/beagle.h:805
	BG_READ_USBPD_NO_HEADER = 3
	// BG_READ_USBPD_NO_DATA as defined in beagle/beagle.h:806
	BG_READ_USBPD_NO_DATA = 4
	// BG_READ_USBPD_NO_CRC as defined in beagle/beagle.h:807
	BG_READ_USBPD_NO_CRC = 5
	// BG_READ_USBPD_NO_EOP as defined in beagle/beagle.h:808
	BG_READ_USBPD_NO_EOP = 6
	// BG_READ_USBPD_ERR_BAD_CRC as defined in beagle/beagle.h:809
	BG_READ_USBPD_ERR_BAD_CRC = 16777216
	// BG_READ_USBPD_ERR_UNKNOWN_TYPE as defined in beagle/beagle.h:810
	BG_READ_USBPD_ERR_UNKNOWN_TYPE = 33554432
	// BG_EVENT_USB_HOST_DISCONNECT as defined in beagle/beagle.h:812
	BG_EVENT_USB_HOST_DISCONNECT = 256
	// BG_EVENT_USB_TARGET_DISCONNECT as defined in beagle/beagle.h:813
	BG_EVENT_USB_TARGET_DISCONNECT = 512
	// BG_EVENT_USB_HOST_CONNECT as defined in beagle/beagle.h:814
	BG_EVENT_USB_HOST_CONNECT = 1024
	// BG_EVENT_USB_TARGET_CONNECT as defined in beagle/beagle.h:815
	BG_EVENT_USB_TARGET_CONNECT = 2048
	// BG_EVENT_USB_RESET as defined in beagle/beagle.h:816
	BG_EVENT_USB_RESET = 4096
	// BG_EVENT_USB_DIGITAL_INPUT_MASK as defined in beagle/beagle.h:821
	BG_EVENT_USB_DIGITAL_INPUT_MASK = 15
	// BG_EVENT_USB_CHIRP_J as defined in beagle/beagle.h:822
	BG_EVENT_USB_CHIRP_J = 8192
	// BG_EVENT_USB_CHIRP_K as defined in beagle/beagle.h:823
	BG_EVENT_USB_CHIRP_K = 16384
	// BG_EVENT_USB_SPEED_UNKNOWN as defined in beagle/beagle.h:824
	BG_EVENT_USB_SPEED_UNKNOWN = 32768
	// BG_EVENT_USB_LOW_SPEED as defined in beagle/beagle.h:825
	BG_EVENT_USB_LOW_SPEED = 65536
	// BG_EVENT_USB_FULL_SPEED as defined in beagle/beagle.h:826
	BG_EVENT_USB_FULL_SPEED = 131072
	// BG_EVENT_USB_HIGH_SPEED as defined in beagle/beagle.h:827
	BG_EVENT_USB_HIGH_SPEED = 262144
	// BG_EVENT_USB_LOW_OVER_FULL_SPEED as defined in beagle/beagle.h:828
	BG_EVENT_USB_LOW_OVER_FULL_SPEED = 524288
	// BG_EVENT_USB_SUSPEND as defined in beagle/beagle.h:829
	BG_EVENT_USB_SUSPEND = 1048576
	// BG_EVENT_USB_RESUME as defined in beagle/beagle.h:830
	BG_EVENT_USB_RESUME = 2097152
	// BG_EVENT_USB_KEEP_ALIVE as defined in beagle/beagle.h:831
	BG_EVENT_USB_KEEP_ALIVE = 4194304
	// BG_EVENT_USB_DIGITAL_INPUT as defined in beagle/beagle.h:832
	BG_EVENT_USB_DIGITAL_INPUT = 8388608
	// BG_EVENT_USB_OTG_HNP as defined in beagle/beagle.h:833
	BG_EVENT_USB_OTG_HNP = 16777216
	// BG_EVENT_USB_OTG_SRP_DATA_PULSE as defined in beagle/beagle.h:834
	BG_EVENT_USB_OTG_SRP_DATA_PULSE = 33554432
	// BG_EVENT_USB_OTG_SRP_VBUS_PULSE as defined in beagle/beagle.h:835
	BG_EVENT_USB_OTG_SRP_VBUS_PULSE = 67108864
	// BG_EVENT_USB_SMA_EXTIN_DETECTED as defined in beagle/beagle.h:840
	BG_EVENT_USB_SMA_EXTIN_DETECTED = 134217728
	// BG_EVENT_USB_CHIRP_DETECTED as defined in beagle/beagle.h:841
	BG_EVENT_USB_CHIRP_DETECTED = 128
	// BG_EVENT_USB_VBUS_TRIGGER as defined in beagle/beagle.h:843
	BG_EVENT_USB_VBUS_TRIGGER = 134217728
	// BG_EVENT_USB_COMPLEX_TIMER as defined in beagle/beagle.h:844
	BG_EVENT_USB_COMPLEX_TIMER = 268435456
	// BG_EVENT_USB_CROSS_TRIGGER as defined in beagle/beagle.h:845
	BG_EVENT_USB_CROSS_TRIGGER = 536870912
	// BG_EVENT_USB_COMPLEX_TRIGGER as defined in beagle/beagle.h:846
	BG_EVENT_USB_COMPLEX_TRIGGER = 1073741824
	// BG_EVENT_USB_TRIGGER as defined in beagle/beagle.h:847
	BG_EVENT_USB_TRIGGER = 2147483648
	// BG_EVENT_USB_TRIGGER_STATE_MASK as defined in beagle/beagle.h:848
	BG_EVENT_USB_TRIGGER_STATE_MASK = 112
	// BG_EVENT_USB_TRIGGER_STATE_SHIFT as defined in beagle/beagle.h:849
	BG_EVENT_USB_TRIGGER_STATE_SHIFT = 4
	// BG_EVENT_USB_TRIGGER_STATE_0 as defined in beagle/beagle.h:850
	BG_EVENT_USB_TRIGGER_STATE_0 = 0
	// BG_EVENT_USB_TRIGGER_STATE_1 as defined in beagle/beagle.h:851
	BG_EVENT_USB_TRIGGER_STATE_1 = 16
	// BG_EVENT_USB_TRIGGER_STATE_2 as defined in beagle/beagle.h:852
	BG_EVENT_USB_TRIGGER_STATE_2 = 32
	// BG_EVENT_USB_TRIGGER_STATE_3 as defined in beagle/beagle.h:853
	BG_EVENT_USB_TRIGGER_STATE_3 = 48
	// BG_EVENT_USB_TRIGGER_STATE_4 as defined in beagle/beagle.h:854
	BG_EVENT_USB_TRIGGER_STATE_4 = 64
	// BG_EVENT_USB_TRIGGER_STATE_5 as defined in beagle/beagle.h:855
	BG_EVENT_USB_TRIGGER_STATE_5 = 80
	// BG_EVENT_USB_TRIGGER_STATE_6 as defined in beagle/beagle.h:856
	BG_EVENT_USB_TRIGGER_STATE_6 = 96
	// BG_EVENT_USB_TRIGGER_STATE_7 as defined in beagle/beagle.h:857
	BG_EVENT_USB_TRIGGER_STATE_7 = 112
	// BG_EVENT_USB_LFPS as defined in beagle/beagle.h:859
	BG_EVENT_USB_LFPS = 4096
	// BG_EVENT_USB_LTSSM as defined in beagle/beagle.h:860
	BG_EVENT_USB_LTSSM = 8192
	// BG_EVENT_USB_VBUS_PRESENT as defined in beagle/beagle.h:861
	BG_EVENT_USB_VBUS_PRESENT = 65536
	// BG_EVENT_USB_VBUS_ABSENT as defined in beagle/beagle.h:862
	BG_EVENT_USB_VBUS_ABSENT = 131072
	// BG_EVENT_USB_SCRAMBLING_ENABLED as defined in beagle/beagle.h:863
	BG_EVENT_USB_SCRAMBLING_ENABLED = 262144
	// BG_EVENT_USB_SCRAMBLING_DISABLED as defined in beagle/beagle.h:864
	BG_EVENT_USB_SCRAMBLING_DISABLED = 524288
	// BG_EVENT_USB_POLARITY_NORMAL as defined in beagle/beagle.h:865
	BG_EVENT_USB_POLARITY_NORMAL = 1048576
	// BG_EVENT_USB_POLARITY_REVERSED as defined in beagle/beagle.h:866
	BG_EVENT_USB_POLARITY_REVERSED = 2097152
	// BG_EVENT_USB_PHY_ERROR as defined in beagle/beagle.h:867
	BG_EVENT_USB_PHY_ERROR = 4194304
	// BG_EVENT_USB_LTSSM_MASK as defined in beagle/beagle.h:868
	BG_EVENT_USB_LTSSM_MASK = 255
	// BG_EVENT_USB_LTSSM_STATE_UNKNOWN as defined in beagle/beagle.h:869
	BG_EVENT_USB_LTSSM_STATE_UNKNOWN = 0
	// BG_EVENT_USB_LTSSM_STATE_SS_DISABLED as defined in beagle/beagle.h:870
	BG_EVENT_USB_LTSSM_STATE_SS_DISABLED = 1
	// BG_EVENT_USB_LTSSM_STATE_SS_INACTIVE as defined in beagle/beagle.h:871
	BG_EVENT_USB_LTSSM_STATE_SS_INACTIVE = 2
	// BG_EVENT_USB_LTSSM_STATE_RX_DETECT_RESET as defined in beagle/beagle.h:872
	BG_EVENT_USB_LTSSM_STATE_RX_DETECT_RESET = 3
	// BG_EVENT_USB_LTSSM_STATE_RX_DETECT_ACTIVE as defined in beagle/beagle.h:873
	BG_EVENT_USB_LTSSM_STATE_RX_DETECT_ACTIVE = 4
	// BG_EVENT_USB_LTSSM_STATE_POLLING_LFPS as defined in beagle/beagle.h:874
	BG_EVENT_USB_LTSSM_STATE_POLLING_LFPS = 5
	// BG_EVENT_USB_LTSSM_STATE_POLLING_RXEQ as defined in beagle/beagle.h:875
	BG_EVENT_USB_LTSSM_STATE_POLLING_RXEQ = 6
	// BG_EVENT_USB_LTSSM_STATE_POLLING_ACTIVE as defined in beagle/beagle.h:876
	BG_EVENT_USB_LTSSM_STATE_POLLING_ACTIVE = 7
	// BG_EVENT_USB_LTSSM_STATE_POLLING_CONFIG as defined in beagle/beagle.h:877
	BG_EVENT_USB_LTSSM_STATE_POLLING_CONFIG = 8
	// BG_EVENT_USB_LTSSM_STATE_POLLING_IDLE as defined in beagle/beagle.h:878
	BG_EVENT_USB_LTSSM_STATE_POLLING_IDLE = 9
	// BG_EVENT_USB_LTSSM_STATE_U0 as defined in beagle/beagle.h:879
	BG_EVENT_USB_LTSSM_STATE_U0 = 10
	// BG_EVENT_USB_LTSSM_STATE_U1 as defined in beagle/beagle.h:880
	BG_EVENT_USB_LTSSM_STATE_U1 = 11
	// BG_EVENT_USB_LTSSM_STATE_U2 as defined in beagle/beagle.h:881
	BG_EVENT_USB_LTSSM_STATE_U2 = 12
	// BG_EVENT_USB_LTSSM_STATE_U3 as defined in beagle/beagle.h:882
	BG_EVENT_USB_LTSSM_STATE_U3 = 13
	// BG_EVENT_USB_LTSSM_STATE_RECOVERY_ACTIVE as defined in beagle/beagle.h:883
	BG_EVENT_USB_LTSSM_STATE_RECOVERY_ACTIVE = 14
	// BG_EVENT_USB_LTSSM_STATE_RECOVERY_CONFIG as defined in beagle/beagle.h:884
	BG_EVENT_USB_LTSSM_STATE_RECOVERY_CONFIG = 15
	// BG_EVENT_USB_LTSSM_STATE_RECOVERY_IDLE as defined in beagle/beagle.h:885
	BG_EVENT_USB_LTSSM_STATE_RECOVERY_IDLE = 16
	// BG_EVENT_USB_LTSSM_STATE_HOT_RESET_ACTIVE as defined in beagle/beagle.h:886
	BG_EVENT_USB_LTSSM_STATE_HOT_RESET_ACTIVE = 17
	// BG_EVENT_USB_LTSSM_STATE_HOT_RESET_EXIT as defined in beagle/beagle.h:887
	BG_EVENT_USB_LTSSM_STATE_HOT_RESET_EXIT = 18
	// BG_EVENT_USB_LTSSM_STATE_LOOPBACK_ACTIVE as defined in beagle/beagle.h:888
	BG_EVENT_USB_LTSSM_STATE_LOOPBACK_ACTIVE = 19
	// BG_EVENT_USB_LTSSM_STATE_LOOPBACK_EXIT as defined in beagle/beagle.h:889
	BG_EVENT_USB_LTSSM_STATE_LOOPBACK_EXIT = 20
	// BG_EVENT_USB_LTSSM_STATE_COMPLIANCE as defined in beagle/beagle.h:890
	BG_EVENT_USB_LTSSM_STATE_COMPLIANCE = 21
	// BG_EVENT_USB_SMA_EXTIN_ASSERTED as defined in beagle/beagle.h:891
	BG_EVENT_USB_SMA_EXTIN_ASSERTED = 16777216
	// BG_EVENT_USB_SMA_EXTIN_DEASSERTED as defined in beagle/beagle.h:892
	BG_EVENT_USB_SMA_EXTIN_DEASSERTED = 33554432
	// BG_EVENT_USB_TRIGGER_5GBIT_START as defined in beagle/beagle.h:893
	BG_EVENT_USB_TRIGGER_5GBIT_START = 67108864
	// BG_EVENT_USB_TRIGGER_5GBIT_STOP as defined in beagle/beagle.h:894
	BG_EVENT_USB_TRIGGER_5GBIT_STOP = 134217728
	// BG_EVENT_USBPD_CC_MASK as defined in beagle/beagle.h:896
	BG_EVENT_USBPD_CC_MASK = 4026531840
	// BG_EVENT_USBPD_CC_SHIFT as defined in beagle/beagle.h:897
	BG_EVENT_USBPD_CC_SHIFT = 28
	// BG_EVENT_USBPD_CC1 as defined in beagle/beagle.h:898
	BG_EVENT_USBPD_CC1 = 0
	// BG_EVENT_USBPD_CC2 as defined in beagle/beagle.h:899
	BG_EVENT_USBPD_CC2 = 268435456
	// BG_EVENT_USBPD_POL_CHANGE as defined in beagle/beagle.h:900
	BG_EVENT_USBPD_POL_CHANGE = 8
	// BG_EVENT_USBPD_SOP_MASK as defined in beagle/beagle.h:901
	BG_EVENT_USBPD_SOP_MASK = 7
	// BG_EVENT_USBPD_SOP as defined in beagle/beagle.h:902
	BG_EVENT_USBPD_SOP = 0
	// BG_EVENT_USBPD_SOP_PRIME as defined in beagle/beagle.h:903
	BG_EVENT_USBPD_SOP_PRIME = 1
	// BG_EVENT_USBPD_SOP_DPRIME as defined in beagle/beagle.h:904
	BG_EVENT_USBPD_SOP_DPRIME = 2
	// BG_EVENT_USBPD_SOP_PRIME_DEBUG as defined in beagle/beagle.h:905
	BG_EVENT_USBPD_SOP_PRIME_DEBUG = 3
	// BG_EVENT_USBPD_SOP_DPRIME_DEBUG as defined in beagle/beagle.h:906
	BG_EVENT_USBPD_SOP_DPRIME_DEBUG = 4
	// BG_EVENT_USBPD_HARD_RESET as defined in beagle/beagle.h:907
	BG_EVENT_USBPD_HARD_RESET = 6
	// BG_EVENT_USBPD_CABLE_RESET as defined in beagle/beagle.h:908
	BG_EVENT_USBPD_CABLE_RESET = 7
	// BG_EVENT_USBPD_EXTENDED_HEADER as defined in beagle/beagle.h:909
	BG_EVENT_USBPD_EXTENDED_HEADER = 16
	// BG_USB_FEATURE_NONE as defined in beagle/beagle.h:911
	BG_USB_FEATURE_NONE = 0
	// BG_USB_FEATURE_USB2_MON as defined in beagle/beagle.h:912
	BG_USB_FEATURE_USB2_MON = 1
	// BG_USB_FEATURE_USB3_MON as defined in beagle/beagle.h:913
	BG_USB_FEATURE_USB3_MON = 2
	// BG_USB_FEATURE_SIMUL_23 as defined in beagle/beagle.h:914
	BG_USB_FEATURE_SIMUL_23 = 4
	// BG_USB_FEATURE_USB3_CMP_TRIG as defined in beagle/beagle.h:915
	BG_USB_FEATURE_USB3_CMP_TRIG = 8
	// BG_USB_FEATURE_USB3_4G_MEM as defined in beagle/beagle.h:916
	BG_USB_FEATURE_USB3_4G_MEM = 32
	// BG_USB_FEATURE_USB2_CMP_TRIG as defined in beagle/beagle.h:917
	BG_USB_FEATURE_USB2_CMP_TRIG = 128
	// BG_USB_FEATURE_CROSS_ANALYZER_SYNC as defined in beagle/beagle.h:918
	BG_USB_FEATURE_CROSS_ANALYZER_SYNC = 256
	// BG_USB_FEATURE_USB3_DOWNLINK as defined in beagle/beagle.h:919
	BG_USB_FEATURE_USB3_DOWNLINK = 512
	// BG_USB_FEATURE_IV_MON_LITE as defined in beagle/beagle.h:920
	BG_USB_FEATURE_IV_MON_LITE = 1024
	// BG_USB_FEATURE_USBPD as defined in beagle/beagle.h:921
	BG_USB_FEATURE_USBPD = 2048
	// BG_USB_LICENSE_LENGTH as defined in beagle/beagle.h:928
	BG_USB_LICENSE_LENGTH = 60
	// BG_USB_CAPTURE_USB3 as defined in beagle/beagle.h:956
	BG_USB_CAPTURE_USB3 = 1
	// BG_USB_CAPTURE_USB2 as defined in beagle/beagle.h:957
	BG_USB_CAPTURE_USB2 = 2
	// BG_USB_CAPTURE_IV_MON_LITE as defined in beagle/beagle.h:958
	BG_USB_CAPTURE_IV_MON_LITE = 8
	// BG_USB_CAPTURE_USBPD as defined in beagle/beagle.h:959
	BG_USB_CAPTURE_USBPD = 16
	// BG_USB2_AUTO_SPEED_DETECT as defined in beagle/beagle.h:1009
	BG_USB2_AUTO_SPEED_DETECT = 0
	// BG_USB2_LOW_SPEED as defined in beagle/beagle.h:1010
	BG_USB2_LOW_SPEED = 1
	// BG_USB2_FULL_SPEED as defined in beagle/beagle.h:1011
	BG_USB2_FULL_SPEED = 2
	// BG_USB2_HIGH_SPEED as defined in beagle/beagle.h:1012
	BG_USB2_HIGH_SPEED = 3
	// BG_USB2_VBUS_OVERRIDE as defined in beagle/beagle.h:1013
	BG_USB2_VBUS_OVERRIDE = 128
	// BG_USB_CAPTURE_SIZE_INFINITE as defined in beagle/beagle.h:1021
	BG_USB_CAPTURE_SIZE_INFINITE = 0
	// BG_USB_CAPTURE_SIZE_SCALE as defined in beagle/beagle.h:1022
	BG_USB_CAPTURE_SIZE_SCALE = 4294967295
	// BG_USB2_DIGITAL_OUT_ENABLE_PIN1 as defined in beagle/beagle.h:1049
	BG_USB2_DIGITAL_OUT_ENABLE_PIN1 = 1
	// BG_USB2_DIGITAL_OUT_PIN1_ACTIVE_HIGH as defined in beagle/beagle.h:1050
	BG_USB2_DIGITAL_OUT_PIN1_ACTIVE_HIGH = 1
	// BG_USB2_DIGITAL_OUT_PIN1_ACTIVE_LOW as defined in beagle/beagle.h:1051
	BG_USB2_DIGITAL_OUT_PIN1_ACTIVE_LOW = 0
	// BG_USB2_DIGITAL_OUT_ENABLE_PIN2 as defined in beagle/beagle.h:1052
	BG_USB2_DIGITAL_OUT_ENABLE_PIN2 = 2
	// BG_USB2_DIGITAL_OUT_PIN2_ACTIVE_HIGH as defined in beagle/beagle.h:1053
	BG_USB2_DIGITAL_OUT_PIN2_ACTIVE_HIGH = 2
	// BG_USB2_DIGITAL_OUT_PIN2_ACTIVE_LOW as defined in beagle/beagle.h:1054
	BG_USB2_DIGITAL_OUT_PIN2_ACTIVE_LOW = 0
	// BG_USB2_DIGITAL_OUT_ENABLE_PIN3 as defined in beagle/beagle.h:1055
	BG_USB2_DIGITAL_OUT_ENABLE_PIN3 = 4
	// BG_USB2_DIGITAL_OUT_PIN3_ACTIVE_HIGH as defined in beagle/beagle.h:1056
	BG_USB2_DIGITAL_OUT_PIN3_ACTIVE_HIGH = 4
	// BG_USB2_DIGITAL_OUT_PIN3_ACTIVE_LOW as defined in beagle/beagle.h:1057
	BG_USB2_DIGITAL_OUT_PIN3_ACTIVE_LOW = 0
	// BG_USB2_DIGITAL_OUT_ENABLE_PIN4 as defined in beagle/beagle.h:1058
	BG_USB2_DIGITAL_OUT_ENABLE_PIN4 = 8
	// BG_USB2_DIGITAL_OUT_PIN4_ACTIVE_HIGH as defined in beagle/beagle.h:1059
	BG_USB2_DIGITAL_OUT_PIN4_ACTIVE_HIGH = 8
	// BG_USB2_DIGITAL_OUT_PIN4_ACTIVE_LOW as defined in beagle/beagle.h:1060
	BG_USB2_DIGITAL_OUT_PIN4_ACTIVE_LOW = 0
	// BG_USB2_DATA_MATCH_DATA0 as defined in beagle/beagle.h:1101
	BG_USB2_DATA_MATCH_DATA0 = 1
	// BG_USB2_DATA_MATCH_DATA1 as defined in beagle/beagle.h:1102
	BG_USB2_DATA_MATCH_DATA1 = 2
	// BG_USB2_DATA_MATCH_DATA2 as defined in beagle/beagle.h:1103
	BG_USB2_DATA_MATCH_DATA2 = 4
	// BG_USB2_DATA_MATCH_MDATA as defined in beagle/beagle.h:1104
	BG_USB2_DATA_MATCH_MDATA = 8
	// BG_USB2_DIGITAL_IN_ENABLE_PIN1 as defined in beagle/beagle.h:1126
	BG_USB2_DIGITAL_IN_ENABLE_PIN1 = 1
	// BG_USB2_DIGITAL_IN_ENABLE_PIN2 as defined in beagle/beagle.h:1127
	BG_USB2_DIGITAL_IN_ENABLE_PIN2 = 2
	// BG_USB2_DIGITAL_IN_ENABLE_PIN3 as defined in beagle/beagle.h:1128
	BG_USB2_DIGITAL_IN_ENABLE_PIN3 = 4
	// BG_USB2_DIGITAL_IN_ENABLE_PIN4 as defined in beagle/beagle.h:1129
	BG_USB2_DIGITAL_IN_ENABLE_PIN4 = 8
	// BG_USB2_HW_FILTER_PID_SOF as defined in beagle/beagle.h:1137
	BG_USB2_HW_FILTER_PID_SOF = 1
	// BG_USB2_HW_FILTER_PID_IN as defined in beagle/beagle.h:1138
	BG_USB2_HW_FILTER_PID_IN = 2
	// BG_USB2_HW_FILTER_PID_PING as defined in beagle/beagle.h:1139
	BG_USB2_HW_FILTER_PID_PING = 4
	// BG_USB2_HW_FILTER_PID_PRE as defined in beagle/beagle.h:1140
	BG_USB2_HW_FILTER_PID_PRE = 8
	// BG_USB2_HW_FILTER_PID_SPLIT as defined in beagle/beagle.h:1141
	BG_USB2_HW_FILTER_PID_SPLIT = 16
	// BG_USB2_HW_FILTER_SELF as defined in beagle/beagle.h:1142
	BG_USB2_HW_FILTER_SELF = 32
	// BG_USB2_MATCH_HANDSHAKE_MASK_DISABLED as defined in beagle/beagle.h:1247
	BG_USB2_MATCH_HANDSHAKE_MASK_DISABLED = 0
	// BG_USB2_MATCH_HANDSHAKE_MASK_NONE as defined in beagle/beagle.h:1248
	BG_USB2_MATCH_HANDSHAKE_MASK_NONE = 1
	// BG_USB2_MATCH_HANDSHAKE_MASK_ACK as defined in beagle/beagle.h:1249
	BG_USB2_MATCH_HANDSHAKE_MASK_ACK = 2
	// BG_USB2_MATCH_HANDSHAKE_MASK_NAK as defined in beagle/beagle.h:1250
	BG_USB2_MATCH_HANDSHAKE_MASK_NAK = 4
	// BG_USB2_MATCH_HANDSHAKE_MASK_NYET as defined in beagle/beagle.h:1251
	BG_USB2_MATCH_HANDSHAKE_MASK_NYET = 8
	// BG_USB2_MATCH_HANDSHAKE_MASK_STALL as defined in beagle/beagle.h:1252
	BG_USB2_MATCH_HANDSHAKE_MASK_STALL = 16
	// BG_USB_COMPLEX_MATCH_ACTION_EXTOUT as defined in beagle/beagle.h:1276
	BG_USB_COMPLEX_MATCH_ACTION_EXTOUT = 1
	// BG_USB_COMPLEX_MATCH_ACTION_TRIGGER as defined in beagle/beagle.h:1277
	BG_USB_COMPLEX_MATCH_ACTION_TRIGGER = 2
	// BG_USB_COMPLEX_MATCH_ACTION_FILTER as defined in beagle/beagle.h:1278
	BG_USB_COMPLEX_MATCH_ACTION_FILTER = 4
	// BG_USB_COMPLEX_MATCH_ACTION_GOTO as defined in beagle/beagle.h:1279
	BG_USB_COMPLEX_MATCH_ACTION_GOTO = 8
	// BG_USB3_PHY_CONFIG_POLARITY_NON_INVERT as defined in beagle/beagle.h:1462
	BG_USB3_PHY_CONFIG_POLARITY_NON_INVERT = 0
	// BG_USB3_PHY_CONFIG_POLARITY_INVERT as defined in beagle/beagle.h:1463
	BG_USB3_PHY_CONFIG_POLARITY_INVERT = 1
	// BG_USB3_PHY_CONFIG_POLARITY_AUTO as defined in beagle/beagle.h:1464
	BG_USB3_PHY_CONFIG_POLARITY_AUTO = 2
	// BG_USB3_PHY_CONFIG_POLARITY_MASK as defined in beagle/beagle.h:1465
	BG_USB3_PHY_CONFIG_POLARITY_MASK = 3
	// BG_USB3_PHY_CONFIG_DESCRAMBLER_ON as defined in beagle/beagle.h:1466
	BG_USB3_PHY_CONFIG_DESCRAMBLER_ON = 0
	// BG_USB3_PHY_CONFIG_DESCRAMBLER_OFF as defined in beagle/beagle.h:1467
	BG_USB3_PHY_CONFIG_DESCRAMBLER_OFF = 4
	// BG_USB3_PHY_CONFIG_DESCRAMBLER_AUTO as defined in beagle/beagle.h:1468
	BG_USB3_PHY_CONFIG_DESCRAMBLER_AUTO = 8
	// BG_USB3_PHY_CONFIG_DESCRAMBLER_MASK as defined in beagle/beagle.h:1469
	BG_USB3_PHY_CONFIG_DESCRAMBLER_MASK = 12
	// BG_USB3_PHY_CONFIG_RXTERM_ON as defined in beagle/beagle.h:1470
	BG_USB3_PHY_CONFIG_RXTERM_ON = 0
	// BG_USB3_PHY_CONFIG_RXTERM_OFF as defined in beagle/beagle.h:1471
	BG_USB3_PHY_CONFIG_RXTERM_OFF = 16
	// BG_USB3_PHY_CONFIG_RXTERM_AUTO as defined in beagle/beagle.h:1472
	BG_USB3_PHY_CONFIG_RXTERM_AUTO = 32
	// BG_USB3_PHY_CONFIG_RXTERM_MASK as defined in beagle/beagle.h:1473
	BG_USB3_PHY_CONFIG_RXTERM_MASK = 48
	// BG_USB3_TRUNCATION_OFF as defined in beagle/beagle.h:1481
	BG_USB3_TRUNCATION_OFF = 0
	// BG_USB3_TRUNCATION_20 as defined in beagle/beagle.h:1482
	BG_USB3_TRUNCATION_20 = 1
	// BG_USB3_TRUNCATION_36 as defined in beagle/beagle.h:1483
	BG_USB3_TRUNCATION_36 = 2
	// BG_USB3_TRUNCATION_68 as defined in beagle/beagle.h:1484
	BG_USB3_TRUNCATION_68 = 3
	// BG_USB3_EQUALIZATION_OFF as defined in beagle/beagle.h:1493
	BG_USB3_EQUALIZATION_OFF = 0
	// BG_USB3_EQUALIZATION_MIN as defined in beagle/beagle.h:1494
	BG_USB3_EQUALIZATION_MIN = 1
	// BG_USB3_EQUALIZATION_MOD as defined in beagle/beagle.h:1495
	BG_USB3_EQUALIZATION_MOD = 2
	// BG_USB3_EQUALIZATION_MAX as defined in beagle/beagle.h:1496
	BG_USB3_EQUALIZATION_MAX = 3
	// BG_USB3_SIMPLE_MATCH_NONE as defined in beagle/beagle.h:1519
	BG_USB3_SIMPLE_MATCH_NONE = 0
	// BG_USB3_SIMPLE_MATCH_SSTX_IPS as defined in beagle/beagle.h:1520
	BG_USB3_SIMPLE_MATCH_SSTX_IPS = 1
	// BG_USB3_SIMPLE_MATCH_SSTX_SLC as defined in beagle/beagle.h:1521
	BG_USB3_SIMPLE_MATCH_SSTX_SLC = 2
	// BG_USB3_SIMPLE_MATCH_SSTX_SHP as defined in beagle/beagle.h:1522
	BG_USB3_SIMPLE_MATCH_SSTX_SHP = 4
	// BG_USB3_SIMPLE_MATCH_SSTX_SDP as defined in beagle/beagle.h:1523
	BG_USB3_SIMPLE_MATCH_SSTX_SDP = 8
	// BG_USB3_SIMPLE_MATCH_SSRX_IPS as defined in beagle/beagle.h:1524
	BG_USB3_SIMPLE_MATCH_SSRX_IPS = 16
	// BG_USB3_SIMPLE_MATCH_SSRX_SLC as defined in beagle/beagle.h:1525
	BG_USB3_SIMPLE_MATCH_SSRX_SLC = 32
	// BG_USB3_SIMPLE_MATCH_SSRX_SHP as defined in beagle/beagle.h:1526
	BG_USB3_SIMPLE_MATCH_SSRX_SHP = 64
	// BG_USB3_SIMPLE_MATCH_SSRX_SDP as defined in beagle/beagle.h:1527
	BG_USB3_SIMPLE_MATCH_SSRX_SDP = 128
	// BG_USB3_SIMPLE_MATCH_SSTX_SLC_CRC_5A_CRC_5B as defined in beagle/beagle.h:1528
	BG_USB3_SIMPLE_MATCH_SSTX_SLC_CRC_5A_CRC_5B = 256
	// BG_USB3_SIMPLE_MATCH_SSTX_SHP_CRC_5 as defined in beagle/beagle.h:1529
	BG_USB3_SIMPLE_MATCH_SSTX_SHP_CRC_5 = 512
	// BG_USB3_SIMPLE_MATCH_SSTX_SHP_CRC_16 as defined in beagle/beagle.h:1530
	BG_USB3_SIMPLE_MATCH_SSTX_SHP_CRC_16 = 1024
	// BG_USB3_SIMPLE_MATCH_SSTX_SDP_CRC as defined in beagle/beagle.h:1531
	BG_USB3_SIMPLE_MATCH_SSTX_SDP_CRC = 2048
	// BG_USB3_SIMPLE_MATCH_SSRX_SLC_CRC_5A_CRC_5B as defined in beagle/beagle.h:1532
	BG_USB3_SIMPLE_MATCH_SSRX_SLC_CRC_5A_CRC_5B = 4096
	// BG_USB3_SIMPLE_MATCH_SSRX_SHP_CRC_5 as defined in beagle/beagle.h:1533
	BG_USB3_SIMPLE_MATCH_SSRX_SHP_CRC_5 = 8192
	// BG_USB3_SIMPLE_MATCH_SSRX_SHP_CRC_16 as defined in beagle/beagle.h:1534
	BG_USB3_SIMPLE_MATCH_SSRX_SHP_CRC_16 = 16384
	// BG_USB3_SIMPLE_MATCH_SSRX_SDP_CRC as defined in beagle/beagle.h:1535
	BG_USB3_SIMPLE_MATCH_SSRX_SDP_CRC = 32768
	// BG_USB3_SIMPLE_MATCH_EVENT_SSTX_LFPS as defined in beagle/beagle.h:1536
	BG_USB3_SIMPLE_MATCH_EVENT_SSTX_LFPS = 65536
	// BG_USB3_SIMPLE_MATCH_EVENT_SSTX_POLARITY as defined in beagle/beagle.h:1537
	BG_USB3_SIMPLE_MATCH_EVENT_SSTX_POLARITY = 131072
	// BG_USB3_SIMPLE_MATCH_EVENT_SSTX_DETECTED as defined in beagle/beagle.h:1538
	BG_USB3_SIMPLE_MATCH_EVENT_SSTX_DETECTED = 4194304
	// BG_USB3_SIMPLE_MATCH_EVENT_SSTX_SCRAMBLE as defined in beagle/beagle.h:1539
	BG_USB3_SIMPLE_MATCH_EVENT_SSTX_SCRAMBLE = 524288
	// BG_USB3_SIMPLE_MATCH_EVENT_SSRX_LFPS as defined in beagle/beagle.h:1540
	BG_USB3_SIMPLE_MATCH_EVENT_SSRX_LFPS = 1048576
	// BG_USB3_SIMPLE_MATCH_EVENT_SSRX_POLARITY as defined in beagle/beagle.h:1541
	BG_USB3_SIMPLE_MATCH_EVENT_SSRX_POLARITY = 2097152
	// BG_USB3_SIMPLE_MATCH_EVENT_SSRX_DETECTED as defined in beagle/beagle.h:1542
	BG_USB3_SIMPLE_MATCH_EVENT_SSRX_DETECTED = 262144
	// BG_USB3_SIMPLE_MATCH_EVENT_SSRX_SCRAMBLE as defined in beagle/beagle.h:1543
	BG_USB3_SIMPLE_MATCH_EVENT_SSRX_SCRAMBLE = 8388608
	// BG_USB3_SIMPLE_MATCH_EVENT_VBUS_PRESENT as defined in beagle/beagle.h:1544
	BG_USB3_SIMPLE_MATCH_EVENT_VBUS_PRESENT = 134217728
	// BG_USB3_SIMPLE_MATCH_EVENT_SSTX_PHYERR as defined in beagle/beagle.h:1545
	BG_USB3_SIMPLE_MATCH_EVENT_SSTX_PHYERR = 268435456
	// BG_USB3_SIMPLE_MATCH_EVENT_SSRX_PHYERR as defined in beagle/beagle.h:1546
	BG_USB3_SIMPLE_MATCH_EVENT_SSRX_PHYERR = 536870912
	// BG_USB3_SIMPLE_MATCH_EVENT_SMA_EXTIN as defined in beagle/beagle.h:1547
	BG_USB3_SIMPLE_MATCH_EVENT_SMA_EXTIN = 1073741824
	// BG_USB_EDGE_RISING as defined in beagle/beagle.h:1548
	BG_USB_EDGE_RISING = 1
	// BG_USB_EDGE_PULSE as defined in beagle/beagle.h:1549
	BG_USB_EDGE_PULSE = 1
	// BG_USB_EDGE_FALLING as defined in beagle/beagle.h:1550
	BG_USB_EDGE_FALLING = 2
	// BG_USB_EDGE_DEVICE_CHIRP as defined in beagle/beagle.h:1551
	BG_USB_EDGE_DEVICE_CHIRP = 1
	// BG_USB_EDGE_HOST_CHIRP as defined in beagle/beagle.h:1552
	BG_USB_EDGE_HOST_CHIRP = 2
	// BG480_TRUNCATION_LENGTH as defined in beagle/beagle.h:1977
	BG480_TRUNCATION_LENGTH = 4
	// BG480V2_USB2_BUFFER_SIZE_256MB as defined in beagle/beagle.h:1978
	BG480V2_USB2_BUFFER_SIZE_256MB = 256
	// BG5000_USB2_BUFFER_SIZE_128MB as defined in beagle/beagle.h:1984
	BG5000_USB2_BUFFER_SIZE_128MB = 128
	// BG5000_USB3_BUFFER_SIZE_2GB as defined in beagle/beagle.h:1985
	BG5000_USB3_BUFFER_SIZE_2GB = 2
	// BG5000_USB3_BUFFER_SIZE_4GB as defined in beagle/beagle.h:1986
	BG5000_USB3_BUFFER_SIZE_4GB = 4
	// BG_MDIO_OPCODE22_WRITE as defined in beagle/beagle.h:2030
	BG_MDIO_OPCODE22_WRITE = 1
	// BG_MDIO_OPCODE22_READ as defined in beagle/beagle.h:2031
	BG_MDIO_OPCODE22_READ = 2
	// BG_MDIO_OPCODE22_ERROR as defined in beagle/beagle.h:2032
	BG_MDIO_OPCODE22_ERROR = 255
	// BG_MDIO_OPCODE45_ADDR as defined in beagle/beagle.h:2033
	BG_MDIO_OPCODE45_ADDR = 0
	// BG_MDIO_OPCODE45_WRITE as defined in beagle/beagle.h:2034
	BG_MDIO_OPCODE45_WRITE = 1
	// BG_MDIO_OPCODE45_READ_POSTINC as defined in beagle/beagle.h:2035
	BG_MDIO_OPCODE45_READ_POSTINC = 2
	// BG_MDIO_OPCODE45_READ as defined in beagle/beagle.h:2036
	BG_MDIO_OPCODE45_READ = 3
	// BG_HEADER_USBPD_STANDARD_MASK as defined in beagle/beagle.h:2096
	BG_HEADER_USBPD_STANDARD_MASK = 65535
	// BG_HEADER_USBPD_EXTENDED_MASK as defined in beagle/beagle.h:2097
	BG_HEADER_USBPD_EXTENDED_MASK = 4294901760
)

// BeagleStatus as declared in beagle/beagle.h:118
type BeagleStatus int32

// BeagleStatus enumeration from beagle/beagle.h:118
const (
	BG_OK                                          = iota
	BG_UNABLE_TO_LOAD_LIBRARY                      = -1
	BG_UNABLE_TO_LOAD_DRIVER                       = -2
	BG_UNABLE_TO_LOAD_FUNCTION                     = -3
	BG_INCOMPATIBLE_LIBRARY                        = -4
	BG_INCOMPATIBLE_DEVICE                         = -5
	BG_INCOMPATIBLE_DRIVER                         = -6
	BG_COMMUNICATION_ERROR                         = -7
	BG_UNABLE_TO_OPEN                              = -8
	BG_UNABLE_TO_CLOSE                             = -9
	BG_INVALID_HANDLE                              = -10
	BG_CONFIG_ERROR                                = -11
	BG_UNKNOWN_PROTOCOL                            = -12
	BG_STILL_ACTIVE                                = -13
	BG_FUNCTION_NOT_AVAILABLE                      = -14
	BG_INVALID_LICENSE                             = -15
	BG_CAPTURE_NOT_TRIGGERED                       = -16
	BG_CAPTURE_NOT_READY_FOR_DOWNLOAD              = -17
	BG_COMMTEST_NOT_AVAILABLE                      = -100
	BG_COMMTEST_NOT_ENABLED                        = -101
	BG_I2C_NOT_AVAILABLE                           = -200
	BG_I2C_NOT_ENABLED                             = -201
	BG_SPI_NOT_AVAILABLE                           = -300
	BG_SPI_NOT_ENABLED                             = -301
	BG_USB_NOT_AVAILABLE                           = -400
	BG_USB_NOT_ENABLED                             = -401
	BG_USB2_NOT_ENABLED                            = -402
	BG_USB3_NOT_ENABLED                            = -403
	BG_CROSS_ANALYZER_SYNC_DISTURBED_RE_ENABLE     = -410
	BG_CROSS_ANALYZER_SYNC_DISTURBED_RECONNECT     = -411
	BG_CROSS_ANALYZER_SYNC_UNLICENSED_SELF         = -412
	BG_CROSS_ANALYZER_SYNC_UNLICENSED_OTHER        = -413
	BG_COMPLEX_CONFIG_ERROR_NO_STATES              = -450
	BG_COMPLEX_CONFIG_ERROR_DATA_PACKET_TYPE       = -451
	BG_COMPLEX_CONFIG_ERROR_DATA_FIELD             = -452
	BG_COMPLEX_CONFIG_ERROR_ERR_MATCH_FIELD        = -453
	BG_COMPLEX_CONFIG_ERROR_DATA_RESOURCES         = -454
	BG_COMPLEX_CONFIG_ERROR_DP_MATCH_TYPE          = -455
	BG_COMPLEX_CONFIG_ERROR_DP_MATCH_VAL           = -456
	BG_COMPLEX_CONFIG_ERROR_DP_REQUIRED            = -457
	BG_COMPLEX_CONFIG_ERROR_DP_RESOURCES           = -458
	BG_COMPLEX_CONFIG_ERROR_TIMER_UNIT             = -459
	BG_COMPLEX_CONFIG_ERROR_TIMER_BOUNDS           = -460
	BG_COMPLEX_CONFIG_ERROR_ASYNC_EVENT            = -461
	BG_COMPLEX_CONFIG_ERROR_ASYNC_EDGE             = -462
	BG_COMPLEX_CONFIG_ERROR_ACTION_FILTER          = -463
	BG_COMPLEX_CONFIG_ERROR_ACTION_GOTO_SEL        = -464
	BG_COMPLEX_CONFIG_ERROR_ACTION_GOTO_DEST       = -465
	BG_COMPLEX_CONFIG_ERROR_BAD_VBUS_TRIGGER_TYPE  = -466
	BG_COMPLEX_CONFIG_ERROR_BAD_VBUS_TRIGGER_THRES = -467
	BG_COMPLEX_CONFIG_ERROR_NO_MULTI_VBUS_TRIGGERS = -468
	BG_COMPLEX_CONFIG_ERROR_IV_MONITOR_NOT_ENABLED = -469
	BG_MDIO_NOT_AVAILABLE                          = -500
	BG_MDIO_NOT_ENABLED                            = -501
	BG_MDIO_BAD_TURNAROUND                         = -502
	BG_IV_MON_NULL_PACKET                          = -600
	BG_IV_MON_INVALID_PACKET_LENGTH                = -601
)

// BeagleProtocol as declared in beagle/beagle.h:518
type BeagleProtocol int32

// BeagleProtocol enumeration from beagle/beagle.h:518
const (
	BG_PROTOCOL_NONE     = iota
	BG_PROTOCOL_COMMTEST = 1
	BG_PROTOCOL_USB      = 2
	BG_PROTOCOL_I2C      = 3
	BG_PROTOCOL_SPI      = 4
	BG_PROTOCOL_MDIO     = 5
)

// BeagleCaptureStatus as declared in beagle/beagle.h:573
type BeagleCaptureStatus int32

// BeagleCaptureStatus enumeration from beagle/beagle.h:573
const (
	BG_CAPTURE_STATUS_UNKNOWN          = -1
	BG_CAPTURE_STATUS_INACTIVE         = 0
	BG_CAPTURE_STATUS_SYNC_STANDBY     = 1
	BG_CAPTURE_STATUS_PRE_TRIGGER      = 2
	BG_CAPTURE_STATUS_PRE_TRIGGER_SYNC = 3
	BG_CAPTURE_STATUS_POST_TRIGGER     = 4
	BG_CAPTURE_STATUS_TRANSFER         = 5
	BG_CAPTURE_STATUS_COMPLETE         = 6
)

// BeagleSpiSSPolarity as declared in beagle/beagle.h:671
type BeagleSpiSSPolarity int32

// BeagleSpiSSPolarity enumeration from beagle/beagle.h:671
const (
	BG_SPI_SS_ACTIVE_LOW  = iota
	BG_SPI_SS_ACTIVE_HIGH = 1
)

// BeagleSpiSckSamplingEdge as declared in beagle/beagle.h:679
type BeagleSpiSckSamplingEdge int32

// BeagleSpiSckSamplingEdge enumeration from beagle/beagle.h:679
const (
	BG_SPI_SCK_SAMPLING_EDGE_RISING  = iota
	BG_SPI_SCK_SAMPLING_EDGE_FALLING = 1
)

// BeagleSpiBitorder as declared in beagle/beagle.h:687
type BeagleSpiBitorder int32

// BeagleSpiBitorder enumeration from beagle/beagle.h:687
const (
	BG_SPI_BITORDER_MSB = iota
	BG_SPI_BITORDER_LSB = 1
)

// BeagleUsbTriggerMode as declared in beagle/beagle.h:961
type BeagleUsbTriggerMode int32

// BeagleUsbTriggerMode enumeration from beagle/beagle.h:961
const (
	BG_USB_TRIGGER_MODE_EVENT     = iota
	BG_USB_TRIGGER_MODE_IMMEDIATE = 1
)

// BeagleUsbTargetPower as declared in beagle/beagle.h:977
type BeagleUsbTargetPower int32

// BeagleUsbTargetPower enumeration from beagle/beagle.h:977
const (
	BG_USB_TARGET_POWER_HOST_SUPPLIED = iota
	BG_USB_TARGET_POWER_OFF           = 1
)

// BeagleUsb2CaptureMode as declared in beagle/beagle.h:993
type BeagleUsb2CaptureMode int32

// BeagleUsb2CaptureMode enumeration from beagle/beagle.h:993
const (
	BG_USB2_CAPTURE_REALTIME                 = iota
	BG_USB2_CAPTURE_REALTIME_WITH_PROTECTION = 1
	BG_USB2_CAPTURE_DELAYED_DOWNLOAD         = 2
)

// BeagleUsb2DigitalOutMatchPins as declared in beagle/beagle.h:1069
type BeagleUsb2DigitalOutMatchPins int32

// BeagleUsb2DigitalOutMatchPins enumeration from beagle/beagle.h:1069
const (
	BG_USB2_DIGITAL_OUT_MATCH_PIN3 = 3
	BG_USB2_DIGITAL_OUT_MATCH_PIN4 = 4
)

// BeagleUsb2MatchType as declared in beagle/beagle.h:1078
type BeagleUsb2MatchType int32

// BeagleUsb2MatchType enumeration from beagle/beagle.h:1078
const (
	BG_USB2_MATCH_TYPE_DISABLED  = iota
	BG_USB2_MATCH_TYPE_EQUAL     = 1
	BG_USB2_MATCH_TYPE_NOT_EQUAL = 2
)

// BeagleUsbMatchType as declared in beagle/beagle.h:1168
type BeagleUsbMatchType int32

// BeagleUsbMatchType enumeration from beagle/beagle.h:1168
const (
	BG_USB_MATCH_TYPE_DISABLED      = iota
	BG_USB_MATCH_TYPE_EQUAL         = 1
	BG_USB_MATCH_TYPE_LESS_EQUAL    = 2
	BG_USB_MATCH_TYPE_GREATER_EQUAL = 3
	BG_USB_MATCH_TYPE_NOT_EQUAL     = 4
)

// BeagleUsb2DataMatchDirection as declared in beagle/beagle.h:1179
type BeagleUsb2DataMatchDirection int32

// BeagleUsb2DataMatchDirection enumeration from beagle/beagle.h:1179
const (
	BG_USB2_MATCH_DIRECTION_DISABLED  = iota
	BG_USB2_MATCH_DIRECTION_IN        = 1
	BG_USB2_MATCH_DIRECTION_OUT_SETUP = 2
	BG_USB2_MATCH_DIRECTION_SETUP     = 3
)

// BeagleUsb2PacketType as declared in beagle/beagle.h:1202
type BeagleUsb2PacketType int32

// BeagleUsb2PacketType enumeration from beagle/beagle.h:1202
const (
	BG_USB2_MATCH_PACKET_IN          = 9
	BG_USB2_MATCH_PACKET_OUT         = 1
	BG_USB2_MATCH_PACKET_SETUP       = 13
	BG_USB2_MATCH_PACKET_SOF         = 5
	BG_USB2_MATCH_PACKET_DATA0       = 3
	BG_USB2_MATCH_PACKET_DATA1       = 11
	BG_USB2_MATCH_PACKET_DATA2       = 7
	BG_USB2_MATCH_PACKET_MDATA       = 15
	BG_USB2_MATCH_PACKET_ACK         = 2
	BG_USB2_MATCH_PACKET_NAK         = 10
	BG_USB2_MATCH_PACKET_STALL       = 14
	BG_USB2_MATCH_PACKET_NYET        = 6
	BG_USB2_MATCH_PACKET_PRE         = 12
	BG_USB2_MATCH_PACKET_ERR         = 268
	BG_USB2_MATCH_PACKET_SPLIT       = 8
	BG_USB2_MATCH_PACKET_EXT         = 0
	BG_USB2_MATCH_PACKET_ANY         = 16
	BG_USB2_MATCH_PACKET_DATA0_DATA1 = 32
	BG_USB2_MATCH_PACKET_DATAX       = 64
	BG_USB2_MATCH_PACKET_SUBPID_MASK = 256
	BG_USB2_MATCH_PACKET_ERROR       = 4096
)

// BeagleUsb2DataMatchPrefix as declared in beagle/beagle.h:1233
type BeagleUsb2DataMatchPrefix int32

// BeagleUsb2DataMatchPrefix enumeration from beagle/beagle.h:1233
const (
	BG_USB2_MATCH_PREFIX_DISABLED     = iota
	BG_USB2_MATCH_PREFIX_IN           = 1
	BG_USB2_MATCH_PREFIX_OUT          = 2
	BG_USB2_MATCH_PREFIX_SETUP        = 3
	BG_USB2_MATCH_PREFIX_CSPLIT       = 4
	BG_USB2_MATCH_PREFIX_CSPLIT_IN    = 5
	BG_USB2_MATCH_PREFIX_SSPLIT_OUT   = 6
	BG_USB2_MATCH_PREFIX_SSPLIT_SETUP = 7
)

// BeagleUsb2ErrorType as declared in beagle/beagle.h:1253
type BeagleUsb2ErrorType int32

// BeagleUsb2ErrorType enumeration from beagle/beagle.h:1253
const (
	BG_USB2_MATCH_CRC_DONT_CARE          = iota
	BG_USB2_MATCH_CRC_VALID              = 1
	BG_USB2_MATCH_CRC_INVALID            = 2
	BG_USB2_MATCH_ERR_MASK_CORRUPTED_PID = 16
	BG_USB2_MATCH_ERR_MASK_CRC           = 32
	BG_USB2_MATCH_ERR_MASK_RXERROR       = 64
	BG_USB2_MATCH_ERR_MASK_JABBER        = 128
)

// BeagleUsb2MatchModifier as declared in beagle/beagle.h:1266
type BeagleUsb2MatchModifier int32

// BeagleUsb2MatchModifier enumeration from beagle/beagle.h:1266
const (
	BG_USB2_MATCH_MODIFIER_0 = iota
	BG_USB2_MATCH_MODIFIER_1 = 1
	BG_USB2_MATCH_MODIFIER_2 = 2
	BG_USB2_MATCH_MODIFIER_3 = 3
)

// BeagleUsbTimerUnit as declared in beagle/beagle.h:1301
type BeagleUsbTimerUnit int32

// BeagleUsbTimerUnit enumeration from beagle/beagle.h:1301
const (
	BG_USB_TIMER_UNIT_DISABLED = iota
	BG_USB_TIMER_UNIT_NS       = 1
	BG_USB_TIMER_UNIT_US       = 2
	BG_USB_TIMER_UNIT_MS       = 3
	BG_USB_TIMER_UNIT_SEC      = 4
)

// BeagleUsb2AsyncEventType as declared in beagle/beagle.h:1322
type BeagleUsb2AsyncEventType int32

// BeagleUsb2AsyncEventType enumeration from beagle/beagle.h:1322
const (
	BG_USB2_COMPLEX_MATCH_EVENT_DIGIN1        = iota
	BG_USB2_COMPLEX_MATCH_EVENT_DIGIN2        = 1
	BG_USB2_COMPLEX_MATCH_EVENT_DIGIN3        = 2
	BG_USB2_COMPLEX_MATCH_EVENT_DIGIN4        = 3
	BG_USB2_COMPLEX_MATCH_EVENT_CHIRP         = 13
	BG_USB2_COMPLEX_MATCH_EVENT_SMA_EXTIN     = 14
	BG_USB2_COMPLEX_MATCH_EVENT_CROSS_TRIGGER = 15
	BG_USB2_COMPLEX_MATCH_EVENT_VBUS_TRIGGER  = 16
)

// BeagleUsb2VbusTriggerType as declared in beagle/beagle.h:1339
type BeagleUsb2VbusTriggerType int32

// BeagleUsb2VbusTriggerType enumeration from beagle/beagle.h:1339
const (
	BG_USB2_VBUS_TRIGGER_TYPE_CURRENT = 1
	BG_USB2_VBUS_TRIGGER_TYPE_VOLTAGE = 2
)

// BeagleUsbExtoutType as declared in beagle/beagle.h:1405
type BeagleUsbExtoutType int32

// BeagleUsbExtoutType enumeration from beagle/beagle.h:1405
const (
	BG_USB_EXTOUT_LOW       = iota
	BG_USB_EXTOUT_HIGH      = 1
	BG_USB_EXTOUT_POS_PULSE = 2
	BG_USB_EXTOUT_NEG_PULSE = 3
	BG_USB_EXTOUT_TOGGLE_0  = 4
	BG_USB_EXTOUT_TOGGLE_1  = 5
)

// BeagleMemoryTestResult as declared in beagle/beagle.h:1423
type BeagleMemoryTestResult int32

// BeagleMemoryTestResult enumeration from beagle/beagle.h:1423
const (
	BG_USB_MEMORY_TEST_PASS = iota
	BG_USB_MEMORY_TEST_FAIL = 1
)

// BeagleUsb3ExtoutMode as declared in beagle/beagle.h:1553
type BeagleUsb3ExtoutMode int32

// BeagleUsb3ExtoutMode enumeration from beagle/beagle.h:1553
const (
	BG_USB3_EXTOUT_DISABLED     = iota
	BG_USB3_EXTOUT_TRIGGER_MODE = 1
	BG_USB3_EXTOUT_EVENTS_MODE  = 2
)

// BeagleUsb3IPSType as declared in beagle/beagle.h:1562
type BeagleUsb3IPSType int32

// BeagleUsb3IPSType enumeration from beagle/beagle.h:1562
const (
	BG_USB3_IPS_TYPE_DISABLED = iota
	BG_USB3_IPS_TYPE_TS1      = 1
	BG_USB3_IPS_TYPE_TS2      = 2
	BG_USB3_IPS_TYPE_TSEQ     = 3
	BG_USB3_IPS_TYPE_TSx      = 4
	BG_USB3_IPS_TYPE_TS_ANY   = 5
)

// BeagleUsbSource as declared in beagle/beagle.h:1596
type BeagleUsbSource int32

// BeagleUsbSource enumeration from beagle/beagle.h:1596
const (
	BG_USB_SOURCE_USB3_ASYNC = iota
	BG_USB_SOURCE_USB3_RX    = 1
	BG_USB_SOURCE_USB3_TX    = 2
	BG_USB_SOURCE_USB2       = 3
	BG_USB_SOURCE_IV_MON     = 4
	BG_USB_SOURCE_USBPD      = 5
)

// BeagleUsb3PacketType as declared in beagle/beagle.h:1624
type BeagleUsb3PacketType int32

// BeagleUsb3PacketType enumeration from beagle/beagle.h:1624
const (
	BG_USB3_MATCH_PACKET_SLC         = iota
	BG_USB3_MATCH_PACKET_SHP         = 1
	BG_USB3_MATCH_PACKET_SDP         = 2
	BG_USB3_MATCH_PACKET_SHP_SDP     = 3
	BG_USB3_MATCH_PACKET_TSx         = 4
	BG_USB3_MATCH_PACKET_TSEQ        = 5
	BG_USB3_MATCH_PACKET_ERROR       = 6
	BG_USB3_MATCH_PACKET_5GBIT_START = 7
	BG_USB3_MATCH_PACKET_5GBIT_STOP  = 8
)

// BeagleUsb3ErrorType as declared in beagle/beagle.h:1639
type BeagleUsb3ErrorType int32

// BeagleUsb3ErrorType enumeration from beagle/beagle.h:1639
const (
	BG_USB3_MATCH_CRC_DONT_CARE    = iota
	BG_USB3_MATCH_CRC_1_VALID      = 1
	BG_USB3_MATCH_CRC_2_VALID      = 2
	BG_USB3_MATCH_CRC_BOTH_VALID   = 3
	BG_USB3_MATCH_CRC_EITHER_FAIL  = 4
	BG_USB3_MATCH_CRC_1_FAIL       = 5
	BG_USB3_MATCH_CRC_2_FAIL       = 6
	BG_USB3_MATCH_CRC_BOTH_FAIL    = 7
	BG_USB3_MATCH_ERR_MASK_CRC     = 16
	BG_USB3_MATCH_ERR_MASK_FRAMING = 32
	BG_USB3_MATCH_ERR_MASK_UNKNOWN = 64
)

// BeagleUsb3MatchModifier as declared in beagle/beagle.h:1656
type BeagleUsb3MatchModifier int32

// BeagleUsb3MatchModifier enumeration from beagle/beagle.h:1656
const (
	BG_USB3_MATCH_MODIFIER_0 = iota
	BG_USB3_MATCH_MODIFIER_1 = 1
	BG_USB3_MATCH_MODIFIER_2 = 2
	BG_USB3_MATCH_MODIFIER_3 = 3
)

// BeagleUsb3AsyncEventType as declared in beagle/beagle.h:1695
type BeagleUsb3AsyncEventType int32

// BeagleUsb3AsyncEventType enumeration from beagle/beagle.h:1695
const (
	BG_USB3_COMPLEX_MATCH_EVENT_SSTX_LFPS     = iota
	BG_USB3_COMPLEX_MATCH_EVENT_SSTX_POLARITY = 1
	BG_USB3_COMPLEX_MATCH_EVENT_SSTX_DETECTED = 2
	BG_USB3_COMPLEX_MATCH_EVENT_SSTX_SCRAMBLE = 3
	BG_USB3_COMPLEX_MATCH_EVENT_SSRX_LFPS     = 4
	BG_USB3_COMPLEX_MATCH_EVENT_SSRX_POLARITY = 5
	BG_USB3_COMPLEX_MATCH_EVENT_SSRX_DETECTED = 6
	BG_USB3_COMPLEX_MATCH_EVENT_SSRX_SCRAMBLE = 7
	BG_USB3_COMPLEX_MATCH_EVENT_CROSS_TRIGGER = 8
	BG_USB3_COMPLEX_MATCH_EVENT_VBUS_PRESENT  = 11
	BG_USB3_COMPLEX_MATCH_EVENT_SSTX_PHYERR   = 12
	BG_USB3_COMPLEX_MATCH_EVENT_SSRX_PHYERR   = 13
	BG_USB3_COMPLEX_MATCH_EVENT_SMA_EXTIN     = 14
)

// BeagleUsb3MemoryTestType as declared in beagle/beagle.h:1785
type BeagleUsb3MemoryTestType int32

// BeagleUsb3MemoryTestType enumeration from beagle/beagle.h:1785
const (
	BG_USB3_MEMORY_TEST_FAST = iota
	BG_USB3_MEMORY_TEST_FULL = 1
	BG_USB3_MEMORY_TEST_SKIP = -1
)

// Beagle5000CrossAnalyzerSyncMode as declared in beagle/beagle.h:1988
type Beagle5000CrossAnalyzerSyncMode int32

// Beagle5000CrossAnalyzerSyncMode enumeration from beagle/beagle.h:1988
const (
	BG5000_CROSS_ANALYZER_SYNC_WAIT   = iota
	BG5000_CROSS_ANALYZER_SYNC_BYPASS = 1
)

// Beagle5000CrossAnalyzerMode as declared in beagle/beagle.h:1996
type Beagle5000CrossAnalyzerMode int32

// Beagle5000CrossAnalyzerMode enumeration from beagle/beagle.h:1996
const (
	BG5000_CROSS_ANALYZER_ACCEPT = iota
	BG5000_CROSS_ANALYZER_IGNORE = 1
)

// BeagleMdioClause as declared in beagle/beagle.h:2021
type BeagleMdioClause int32

// BeagleMdioClause enumeration from beagle/beagle.h:2021
const (
	BG_MDIO_CLAUSE_22    = iota
	BG_MDIO_CLAUSE_45    = 1
	BG_MDIO_CLAUSE_ERROR = 2
)
