// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 21 Jun 2021 16:17:37 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package beagle_bindings

/*
#cgo LDFLAGS: -L${SRCDIR} -lstdc++
#cgo CFLAGS: -I. -DDEBUG -I${SRCDIR}/
#include "beagle.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Beagle type as declared in beagle/beagle.h:201
type Beagle int32

// BeagleVersion as declared in beagle/beagle.h:248
type BeagleVersion struct {
	Software        uint16
	Firmware        uint16
	Hardware        uint16
	Hw_revs_for_sw  uint32
	Fw_revs_for_sw  uint32
	Drv_revs_for_sw uint32
	Api_req_by_sw   uint16
	reffa4c6c5      *C.BeagleVersion
	allocsfa4c6c5   interface{}
}

// BeagleExt as declared in beagle/beagle.h:345
type BeagleExt struct {
	Version        BeagleVersion
	Features       int32
	ref20b37dce    *C.BeagleExt
	allocs20b37dce interface{}
}

// BeagleUsb2PacketMatch as declared in beagle/beagle.h:1097
type BeagleUsb2PacketMatch struct {
	Pid_match_type BeagleUsb2MatchType
	Pid_match_val  byte
	Dev_match_type BeagleUsb2MatchType
	Dev_match_val  byte
	Ep_match_type  BeagleUsb2MatchType
	Ep_match_val   byte
	ref6d1d975d    *C.BeagleUsb2PacketMatch
	allocs6d1d975d interface{}
}

// BeagleUsb2DataMatch as declared in beagle/beagle.h:1114
type BeagleUsb2DataMatch struct {
	Data_match_type   BeagleUsb2MatchType
	Data_match_pid    byte
	Data_length       uint16
	Data              []byte
	Data_valid_length uint16
	Data_valid        []byte
	refc50c0392       *C.BeagleUsb2DataMatch
	allocsc50c0392    interface{}
}

// BeagleUsb2DataProperties as declared in beagle/beagle.h:1199
type BeagleUsb2DataProperties struct {
	Direction           BeagleUsb2DataMatchDirection
	Ep_match_type       BeagleUsbMatchType
	Ep_match_val        byte
	Dev_match_type      BeagleUsbMatchType
	Dev_match_val       byte
	Data_len_match_type BeagleUsbMatchType
	Data_len_match_val  uint16
	refbd6df15f         *C.BeagleUsb2DataProperties
	allocsbd6df15f      interface{}
}

// BeagleUsb2DataMatchUnit as declared in beagle/beagle.h:1298
type BeagleUsb2DataMatchUnit struct {
	Packet_type           BeagleUsb2PacketType
	Prefix                BeagleUsb2DataMatchPrefix
	Handshake             byte
	Data_length           uint16
	Data                  *byte
	Data_valid_length     uint16
	Data_valid            []byte
	Err_match             BeagleUsb2ErrorType
	Data_properties_valid byte
	Data_properties       BeagleUsb2DataProperties
	Match_modifier        BeagleUsb2MatchModifier
	Repeat_count          uint16
	Sticky_action         byte
	Action_mask           byte
	Goto_selector         byte
	ref2e3d4d28           *C.BeagleUsb2DataMatchUnit
	allocs2e3d4d28        interface{}
}

// BeagleUsb2TimerMatchUnit as declared in beagle/beagle.h:1319
type BeagleUsb2TimerMatchUnit struct {
	Timer_unit     BeagleUsbTimerUnit
	Timer_val      uint32
	Action_mask    byte
	Goto_selector  byte
	ref28483831    *C.BeagleUsb2TimerMatchUnit
	allocs28483831 interface{}
}

// BeagleUsb2AsyncEventMatchUnit as declared in beagle/beagle.h:1358
type BeagleUsb2AsyncEventMatchUnit struct {
	Event_type        BeagleUsb2AsyncEventType
	Edge_mask         byte
	Repeat_count      uint16
	Sticky_action     byte
	Action_mask       byte
	Goto_selector     byte
	Vbus_trigger_type BeagleUsb2VbusTriggerType
	Vbus_trigger_val  float32
	ref2726746b       *C.BeagleUsb2AsyncEventMatchUnit
	allocs2726746b    interface{}
}

// BeagleUsb2ComplexMatchState as declared in beagle/beagle.h:1379
type BeagleUsb2ComplexMatchState struct {
	Data_0_valid   byte
	Data_0_match   BeagleUsb2DataMatchUnit
	Data_1_valid   byte
	Data_1_match   BeagleUsb2DataMatchUnit
	Data_2_valid   byte
	Data_2_match   BeagleUsb2DataMatchUnit
	Data_3_valid   byte
	Data_3_match   BeagleUsb2DataMatchUnit
	Timer_valid    byte
	Timer_match    BeagleUsb2TimerMatchUnit
	Async_valid    byte
	Async_match    BeagleUsb2AsyncEventMatchUnit
	Goto_0         byte
	Goto_1         byte
	Goto_2         byte
	refeeb5fe45    *C.BeagleUsb2ComplexMatchState
	allocseeb5fe45 interface{}
}

// BeagleUsb3Channel as declared in beagle/beagle.h:1508
type BeagleUsb3Channel struct {
	Input_equalization_short  byte
	Input_equalization_medium byte
	Input_equalization_long   byte
	Pre_emphasis_short_level  byte
	Pre_emphasis_short_decay  byte
	Pre_emphasis_long_level   byte
	Pre_emphasis_long_decay   byte
	Output_level              byte
	refa8884da4               *C.BeagleUsb3Channel
	allocsa8884da4            interface{}
}

// BeagleUsb3DataProperties as declared in beagle/beagle.h:1621
type BeagleUsb3DataProperties struct {
	Source_match_type    BeagleUsbMatchType
	Source_match_val     BeagleUsbSource
	Ep_match_type        BeagleUsbMatchType
	Ep_match_val         byte
	Dev_match_type       BeagleUsbMatchType
	Dev_match_val        byte
	Stream_id_match_type BeagleUsbMatchType
	Stream_id_match_val  uint16
	Data_len_match_type  BeagleUsbMatchType
	Data_len_match_val   uint16
	ref4962ab7           *C.BeagleUsb3DataProperties
	allocs4962ab7        interface{}
}

// BeagleUsb3DataMatchUnit as declared in beagle/beagle.h:1682
type BeagleUsb3DataMatchUnit struct {
	Packet_type           BeagleUsb3PacketType
	Data_length           uint16
	Data                  *byte
	Data_valid_length     uint16
	Data_valid            *byte
	Err_match             BeagleUsb3ErrorType
	Data_properties_valid byte
	Data_properties       BeagleUsb3DataProperties
	Match_modifier        BeagleUsb3MatchModifier
	Repeat_count          uint16
	Sticky_action         byte
	Action_mask           byte
	Goto_selector         byte
	refb332ac5e           *C.BeagleUsb3DataMatchUnit
	allocsb332ac5e        interface{}
}

// BeagleUsb3TimerMatchUnit as declared in beagle/beagle.h:1692
type BeagleUsb3TimerMatchUnit struct {
	Timer_unit     BeagleUsbTimerUnit
	Timer_val      uint32
	Action_mask    byte
	Goto_selector  byte
	ref91b3e3d9    *C.BeagleUsb3TimerMatchUnit
	allocs91b3e3d9 interface{}
}

// BeagleUsb3AsyncEventMatchUnit as declared in beagle/beagle.h:1724
type BeagleUsb3AsyncEventMatchUnit struct {
	Event_type     BeagleUsb3AsyncEventType
	Edge_mask      byte
	Repeat_count   uint16
	Sticky_action  byte
	Action_mask    byte
	Goto_selector  byte
	ref42414f2d    *C.BeagleUsb3AsyncEventMatchUnit
	allocs42414f2d interface{}
}

// BeagleUsb3ComplexMatchState as declared in beagle/beagle.h:1749
type BeagleUsb3ComplexMatchState struct {
	Tx_data_0_valid byte
	Tx_data_0_match BeagleUsb3DataMatchUnit
	Tx_data_1_valid byte
	Tx_data_1_match BeagleUsb3DataMatchUnit
	Tx_data_2_valid byte
	Tx_data_2_match BeagleUsb3DataMatchUnit
	Rx_data_0_valid byte
	Rx_data_0_match BeagleUsb3DataMatchUnit
	Rx_data_1_valid byte
	Rx_data_1_match BeagleUsb3DataMatchUnit
	Rx_data_2_valid byte
	Rx_data_2_match BeagleUsb3DataMatchUnit
	Timer_valid     byte
	Timer_match     BeagleUsb3TimerMatchUnit
	Async_valid     byte
	Async_match     BeagleUsb3AsyncEventMatchUnit
	Goto_0          byte
	Goto_1          byte
	Goto_2          byte
	ref1e748a4      *C.BeagleUsb3ComplexMatchState
	allocs1e748a4   interface{}
}

// BeagleUsbStatsConfig as declared in beagle/beagle.h:1877
type BeagleUsbStatsConfig struct {
	Auto_config       byte
	Source_match_type BeagleUsbMatchType
	Source_match_val  BeagleUsbSource
	Ep_match_type     BeagleUsbMatchType
	Ep_match_val      byte
	Dev_match_type    BeagleUsbMatchType
	Dev_match_val     byte
	refb3b6387a       *C.BeagleUsbStatsConfig
	allocsb3b6387a    interface{}
}

// BeagleUsb3GenStats as declared in beagle/beagle.h:1918
type BeagleUsb3GenStats struct {
	Link                uint64
	Lbad                uint64
	Slc_crc5            uint64
	Txn                 uint64
	Lmp                 uint64
	Lgo_u1              uint64
	Lgo_u2              uint64
	Lgo_u3              uint64
	Dp                  uint64
	Itp                 uint64
	Shp_crc16_crc5      uint64
	Sdp_crc32           uint64
	Slc_frm_err         uint64
	Shp_frm_err         uint64
	Sdp_end_edb_frm_err uint64
	Iso_ips             uint64
	Para_ips            uint64
	Carry_1k_dp         uint64
	ref3dd10611         *C.BeagleUsb3GenStats
	allocs3dd10611      interface{}
}

// BeagleUsb3ConnStats as declared in beagle/beagle.h:1931
type BeagleUsb3ConnStats struct {
	Txn            uint64
	Dp             uint64
	Ack            uint64
	Nrdy           uint64
	Erdy           uint64
	Retry_ack      uint64
	Carry_1k_dp    uint64
	ref44c1c4ad    *C.BeagleUsb3ConnStats
	allocs44c1c4ad interface{}
}

// BeagleUsb2Stats as declared in beagle/beagle.h:1946
type BeagleUsb2Stats struct {
	Sof            uint64
	Carry_1k_data  uint64
	Data           uint64
	Bad_pid        uint64
	Crc16          uint64
	Crc5           uint64
	Rx_error       uint64
	In_nak         uint64
	Ping_nak       uint64
	ref405ab34b    *C.BeagleUsb2Stats
	allocs405ab34b interface{}
}

// BeagleUsbStats as declared in beagle/beagle.h:1957
type BeagleUsbStats struct {
	Usb3_tx_gen    BeagleUsb3GenStats
	Usb3_rx_gen    BeagleUsb3GenStats
	Usb3_tx_conn   BeagleUsb3ConnStats
	Usb3_rx_conn   BeagleUsb3ConnStats
	Usb2           BeagleUsb2Stats
	refa05986e9    *C.BeagleUsbStats
	allocsa05986e9 interface{}
}
